// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyectoEF;

#nullable disable

namespace proyectoEF.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20250319225155_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("proyectoEF.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("d3b07384-d113-4632-b568-123456789abc"),
                            Nombre = "estudio",
                            Peso = 10
                        },
                        new
                        {
                            CategoriaId = new Guid("a1b2c3d4-e5f6-7890-1234-56789abcdef0"),
                            Nombre = "personal",
                            Peso = 8
                        });
                });

            modelBuilder.Entity("proyectoEF.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("f1e2d3c4-b5a6-7890-0987-654321abcdef"),
                            CategoriaId = new Guid("a1b2c3d4-e5f6-7890-1234-56789abcdef0"),
                            FechaCreacion = new DateTime(2025, 3, 19, 17, 51, 54, 542, DateTimeKind.Local).AddTicks(6441),
                            PrioridadTarea = 2,
                            Titulo = "remesa"
                        },
                        new
                        {
                            TareaId = new Guid("abcdef12-3456-7890-abcd-ef1234567890"),
                            CategoriaId = new Guid("d3b07384-d113-4632-b568-123456789abc"),
                            FechaCreacion = new DateTime(2025, 3, 19, 17, 51, 54, 543, DateTimeKind.Local).AddTicks(9614),
                            PrioridadTarea = 2,
                            Titulo = "curso entity"
                        });
                });

            modelBuilder.Entity("proyectoEF.Models.Tarea", b =>
                {
                    b.HasOne("proyectoEF.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("proyectoEF.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
